language: c
compiler:
  - gcc
  - clang
before_install: sudo apt-get update
install: sudo apt-get install pkg-config libmsgpack-dev libzmq-dev libglib2.0-dev asciidoc autoconf automake
script: ./build.sh
